### ISSUE TITLE
cli_question missing 1 required positional argument: 'secondary'

### ISSUE THREAD

**Issue by jimbob88** [FaithLife-Community/LogosLinuxInstaller#181]
```
2024-09-22 10:45:45 INFO: Using DIALOG: curses
2024-09-22 10:45:54 ERROR: An error occurred in run_control_panel(): cli_question() missing 1 required positional argument: 'secondary'
Traceback (most recent call last):
  File "main.py", line 442, in <module>
  File "main.py", line 419, in main
  File "main.py", line 307, in run_control_panel
  File "main.py", line 292, in run_control_panel
  File "curses/__init__.py", line 94, in wrapper
  File "tui_app.py", line 706, in control_panel_app
  File "tui_app.py", line 245, in run
  File "tui_app.py", line 217, in display
  File "tui_app.py", line 313, in choice_processor
  File "control.py", line 43, in restore
  File "control.py", line 70, in backup_and_restore
TypeError: cli_question() missing 1 required positional argument: 'secondary'
[PYI-47414:ERROR] Failed to execute script 'main' due to unhandled exception!
```

The issue is caused by the following lines: https://github.com/FaithLife-Community/LogosLinuxInstaller/blob/f02e0133670040337b0351de7582034f827e10ba/control.py#L65C4-L77C38

Because `msg.cli_question` now requires a "secondary" (information) line: https://github.com/FaithLife-Community/LogosLinuxInstaller/blob/f02e0133670040337b0351de7582034f827e10ba/msg.py#L189C1-L203C45

Issue exists in the following places:

- [ ] backup_and_restore: [section 1](https://github.com/FaithLife-Community/LogosLinuxInstaller/blob/f02e0133670040337b0351de7582034f827e10ba/control.py#L65C4-L77C38) [section 2](https://github.com/FaithLife-Community/LogosLinuxInstaller/blob/f02e0133670040337b0351de7582034f827e10ba/control.py#L79C1-L91C56)
- [ ] [remove_install_dir](https://github.com/FaithLife-Community/LogosLinuxInstaller/blob/f02e0133670040337b0351de7582034f827e10ba/control.py#L223)
- [ ] [cli_acknowledge_question](https://github.com/FaithLife-Community/LogosLinuxInstaller/blob/f02e0133670040337b0351de7582034f827e10ba/msg.py#L216)
- [ ] [die_if_running](https://github.com/FaithLife-Community/LogosLinuxInstaller/blob/f02e0133670040337b0351de7582034f827e10ba/utils.py#L144C1-L145C52)

**Comment by thw26** [comment]
Thank you for reporting this!
