### ISSUE TITLE
Running indexer via CLI fails due to unpopulated config

### ISSUE THREAD

**Issue by ctrlaltf24** [FaithLife-Community/LogosLinuxInstaller#188]
Will be making PR shortly
```
$ ./main.py --debug --run-indexing
2024-10-05 15:59:50 INFO: Running function: index
Exception in thread <function LogosManager.index.<locals>.run_indexing at 0x75e415ba5800>:
Traceback (most recent call last):
  File "/opt/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/opt/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
TypeError: LogosManager.index.<locals>.run_indexing() got an unexpected keyword argument 'daemon'
Traceback (most recent call last):
  File "/opt/LogosLinuxInstaller/main.py", line 444, in <module>
    main()
  File "/opt/LogosLinuxInstaller/main.py", line 421, in main
    config.ACTION()
  File "/opt/LogosLinuxInstaller/logos.py", line 163, in index
    process = config.processes[config.logos_indexer_exe]
              ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: None
```

**Comment by thw26** [comment]
Please see #161 for ongoing work to fix the CLI optargs.
