### ISSUE TITLE
Installer Fails to Create the Log File on Initial Run

### ISSUE THREAD

**Issue by thw26** [FaithLife-Community/LogosLinuxInstaller#66]
A user reported that he received a FileNotFoundError in chat for the Logo file. We need to investigate why that is.

**Comment by tomsdavis** [comment]
If it helps, I found the same issue:

Traceback (most recent call last):
  File "LogosLinuxInstaller.py", line 324, in <module>
  File "LogosLinuxInstaller.py", line 247, in main
  File "msg.py", line 37, in initialize_logging
  File "logging/__init__.py", line 1231, in __init__
  File "logging/__init__.py", line 1263, in _open
FileNotFoundError: [Errno 2] No such file or directory: '/home/tom/.local/state/Logos_on_Linux/Logos_on_Linux.log'

To get beyond this point I manually created the ~/.local/state/Logos_on_Linux directory, then
`touch Logos_on_Linux.log`
