### ISSUE TITLE
Arch on python version < 3.12, causing install script to error

### ISSUE THREAD

**Issue by andyhunne** [FaithLife-Community/LogosLinuxInstaller#75]
The script errors out complaining about Python 3.12 or highter for .rglob() flag 'case-sentitive'

`Downloading release list for Logos 10...
Traceback (most recent call last):
  File "/home/andy/code/LogosLinuxInstaller/LogosLinuxInstaller.py", line 324, in <module>
    main()
  File "/home/andy/code/LogosLinuxInstaller/LogosLinuxInstaller.py", line 320, in main
    run_control_panel()
  File "/home/andy/code/LogosLinuxInstaller/LogosLinuxInstaller.py", line 238, in run_control_panel
    tui_app.control_panel_app()
  File "/home/andy/code/LogosLinuxInstaller/tui_app.py", line 69, in control_panel_app
    installer.install()
  File "/home/andy/code/LogosLinuxInstaller/installer.py", line 497, in install
    prepare_install()
  File "/home/andy/code/LogosLinuxInstaller/installer.py", line 506, in prepare_install
    choose_install_method()  # We ask user for his desired install method.
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andy/code/LogosLinuxInstaller/installer.py", line 132, in choose_install_method
    utils.find_appimage_files(),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andy/code/LogosLinuxInstaller/utils.py", line 1196, in find_appimage_files
    raise RuntimeError("Python 3.12 or higher is required for .rglob() flag `case-sensitive` ")
RuntimeError: Python 3.12 or higher is required for .rglob() flag `case-sensitive` `

**Comment by andyhunne** [comment]
Should have added, the 'default' Python version on Arch is currently 3.11.8

**Comment by thw26** [comment]
Yes, this was an intentional choice on our part. You will need to build Python from source or download the binary. See the README for dev instructions on how to do this.

**Comment by andyhunne** [comment]
I'm an idiot - I was reading the readme file from ferion11...
Thanks
