### ISSUE TITLE
SteamOS: `pacman` Hits Locked Database

### ISSUE THREAD

**Issue by thw26** [FaithLife-Community/LogosLinuxInstaller#76]
Reported by @jg00dman:

Running on steam os I got this:

```
./LogosLinuxInstaller
:: Synchronising package databases...
error: failed to synchronize all databases (unable to lock database)
Traceback (most recent call last):
  File "[LogosLinuxInstaller.py](http://logoslinuxinstaller.py/)", line 324, in <module>
  File "[LogosLinuxInstaller.py](http://logoslinuxinstaller.py/)", line 320, in main
  File "[LogosLinuxInstaller.py](http://logoslinuxinstaller.py/)", line 238, in run_control_panel
  File "tui_[app.py](http://app.py/)", line 69, in control_panel_app
  File "[installer.py](http://installer.py/)", line 450, in install
  File "[installer.py](http://installer.py/)", line 456, in prepare_install
  File "[installer.py](http://installer.py/)", line 88, in choose_version
  File "[utils.py](http://utils.py/)", line 647, in check_dependencies
  File "[utils.py](http://utils.py/)", line 597, in install_dependencies
  File "[utils.py](http://utils.py/)", line 394, in install_packages
  File "[subprocess.py](http://subprocess.py/)", line 571, in run
subprocess.CalledProcessError: Command 'sudo pacman -Syu --overwrite * --noconfirm --needed patch cabextract samba bc print-manager system-config-printer cups-filters foomatic-db-engine foomatic-db-ppds foomatic-db-nonfree-ppds samba extra-rel/apparmor core-rel/libcurl-gnutls winetricks cabextract appmenu-gtk-module patch bc lib32-libjpeg-turbo qt5-virtualkeyboard wine-staging lib32-giflib lib32-gnutls lib32-mpg123 lib32-v4l-utils lib32-libjpeg-turbo lib32-libxcomposite lib32-ocl-icd lib32-libxslt lib32-gtk3 lib32-gst-plugins-base-libs' returned non-zero exit status 1.
[311690] Failed to execute script 'LogosLinuxInstaller' due to unhandled exception!
```

---
As I see it, SteamOS is complaining it cannot lock the database, which means it either is already locked while a second `pacman` request is being run, or it locked it but something failed in `pacman` that prevented removing the database lock.

**Comment by thw26** [comment]
Notably, John said this happens on Kubuntu, too.
