### ISSUE TITLE
Endless loop when glob() encounters a symlink loop

### ISSUE THREAD

**Issue by tbleher** [FaithLife-Community/LogosLinuxInstaller#91]
I'm currently trying to install Logos using this repo, after having tried (and failing) to use https://github.com/ferion11/LogosLinuxInstaller .
Now it seems that the installer goes into an endless loop, because the files listed inside `~/LogosBible10/data/wine64_bottle` (which I still have around from previous installs) contains symlink loops.
One of the culprits seem to be:
```
thomas@bluelight:~/LogosBible10/data/wine64_bottle/drive_c/users/thomas/AppData/Roaming/Microsoft/Windows$ ls -l Templates
lrwxrwxrwx 1 thomas thomas 13 Apr 13 08:42 Templates -> /home/thomas/
```
But the install contained several symlink loops. The backtrace looks like this:
```
Traceback (most recent call last):
  File "/home/thomas/coding/LogosLinuxInstaller-FaithLife/./LogosLinuxInstaller.py", line 340, in <module>
    main()
  File "/home/thomas/coding/LogosLinuxInstaller-FaithLife/./LogosLinuxInstaller.py", line 336, in main
    run_control_panel()
  File "/home/thomas/coding/LogosLinuxInstaller-FaithLife/./LogosLinuxInstaller.py", line 251, in run_control_panel
    tui_app.control_panel_app()
  File "/home/thomas/coding/LogosLinuxInstaller-FaithLife/tui_app.py", line 83, in control_panel_app
    installer.install()
  File "/home/thomas/coding/LogosLinuxInstaller-FaithLife/installer.py", line 519, in install
    finish_install()
  File "/home/thomas/coding/LogosLinuxInstaller-FaithLife/installer.py", line 537, in finish_install
    if check_existing_install(app):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/coding/LogosLinuxInstaller-FaithLife/installer.py", line 191, in check_existing_install
    if os.path.isdir(drive_c) and any(glob.glob(f"{drive_c}/**/{n}", recursive=True) for n in names):  # noqa: E501
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/coding/LogosLinuxInstaller-FaithLife/installer.py", line 191, in <genexpr>
    if os.path.isdir(drive_c) and any(glob.glob(f"{drive_c}/**/{n}", recursive=True) for n in names):  # noqa: E501
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lib/python3.12/glob.py", line 28, in glob
    return list(iglob(pathname, root_dir=root_dir, dir_fd=dir_fd, recursive=recursive,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lib/python3.12/glob.py", line 96, in _iglob
    for dirname in dirs:
  File "/opt/lib/python3.12/glob.py", line 97, in _iglob
    for name in glob_in_dir(_join(root_dir, dirname), basename, dir_fd, dironly,
  File "/opt/lib/python3.12/glob.py", line 136, in _glob2
    yield from _rlistdir(dirname, dir_fd, dironly,
  File "/opt/lib/python3.12/glob.py", line 186, in _rlistdir
    for y in _rlistdir(path, dir_fd, dironly,
  File "/opt/lib/python3.12/glob.py", line 186, in _rlistdir
    for y in _rlistdir(path, dir_fd, dironly,
  File "/opt/lib/python3.12/glob.py", line 186, in _rlistdir
    for y in _rlistdir(path, dir_fd, dironly,
  [Previous line repeated 14 more times]
  File "/opt/lib/python3.12/glob.py", line 188, in _rlistdir
    yield _join(x, y)
          ^^^^^^^^^^^
  File "/opt/lib/python3.12/glob.py", line 217, in _join
    return os.path.join(dirname, basename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 85, in join
KeyboardInterrupt
```

I think globbing should not follow symlinks, but I have not checked if this is easily possible.

**Comment by tbleher** [comment]
I deleted the old directory and started anew. The installation still seems to take a long time. `strace` shows me paths like the following:

```
newfstatat(AT_FDCWD, "/home/thomas/LogosBible10/data/wine64_bottle/drive_c/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/c:/users/thomas/Music/LogosBible10/data/wine64_bottle/dosdevices/z:/home/thomas/coding/sumo/source/tests/tools/trip/randomTrips/vehicle_insertion/split_action/Logos.exe", 0x7ffdf71d1740, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
```
`/home/thomas/LogosBible10/data/wine64_bottle/drive_c/users/thomas/Music` (which was created by the installer (as cloned yesterday from this repository)) points to my home directory.  `/home/thomas/LogosBible10/data/wine64_bottle/dosdevices/z:` (also created by the installer) points to `/` (the root of the filesystem).

It may not be an infinite loop (I couldn't reproduce with a simple example) but certainly it seems to scan a lot more files than needed.

**Comment by tbleher** [comment]
It looks promising to use `os.walk` instead of `glob.glob` (per https://stackoverflow.com/a/1724723). I'm not an experienced Python programmer, but currently testing a patch for this.

**Comment by thw26** [comment]
Possibly related to #13.
